### ISSUE TITLE
SDF function fail to generate marching cube mesh

### ISSUE THREAD

**Issue by boduan1** [royorel/StyleSDF#11]
I tried with the code with sphere init works fine, but after training the volume renderer, the SDF function seems to have some problem, it can not generate mesh from marching cube (value all >0 or all <0), and depth map it simply gives a planar surface.

I train the code on a single GPU with batch size = 1.

What might be the problem and solution?

**Comment by royorel** [comment]
Hi @boduan1,

First of all what type of data are you training on? If it's not FFHQ or AFHQ I can't really help you because each dataset would probably require minor tweaks to the hyper-parameters.

The other issue is that you only train on batch size of 1, which is not according to the paper. We have never tested the code on such a low batch size and it's probably the reason the training GAN didn't converge. Try to increase the batch size as much as you can.

**Comment by boduan1** [comment]
> Hi @boduan1,
> 
> First of all what type of data are you training on? If it's not FFHQ or AFHQ I can't really help you because each dataset would probably require minor tweaks to the hyper-parameters.
> 
> The other issue is that you only train on batch size of 1, which is not according to the paper. We have never tested the code on such a low batch size and it's probably the reason the training GAN didn't converge. Try to increase the batch size as much as you can.

Thanks for your reply royorel!
I trained it on AFHQ sub dataset with only dog images, which I thought to be easier to converge).
And I tried to increase the batch size, now with batch size 4 on 4 12GB GPUs, and trained only the volume rendering part for half-day for 30k iterations (image size 256). 

I got the same problem that can't generate mesh from marching cube (sdf value all >0 or all <0)
![image](https://user-images.githubusercontent.com/58148182/165503744-e16cc836-9de7-4f97-9bd5-806f6a04a01d.png)

But the image seems to be OK.
![image](https://user-images.githubusercontent.com/58148182/165503169-abfdc7a2-75c0-4170-a6aa-b7c5ee7fbc51.png)

The depth map mesh is planar.
![image](https://user-images.githubusercontent.com/58148182/165503986-4186c59c-346c-40cd-81d5-b0687b8f9d2a.png)

But the initialization gives a good sphere marching cube mesh.
![image](https://user-images.githubusercontent.com/58148182/165504270-16a4bde2-cc89-473e-bb2d-5af8f2794115.png)
and a curved depth map mesh.
![image](https://user-images.githubusercontent.com/58148182/165504602-58d4afac-b5ff-46fc-a50b-3266cb1b6c31.png)

Do you know what might be the problem？

Should the model always be able to generate marching cube mesh or should I train more iterations? The marching cube fails since training from 1k to 30k iterations.

**Comment by royorel** [comment]
@boduan1 

These images are actually not ok, the model failed to converge. The image quality is not what it should be like and there's no change of pose in the dogs' faces. Here's how the volume renderer outputs should look like when the model is converged:
![image](https://user-images.githubusercontent.com/13196935/165506489-6c47f6ab-f006-4643-a4cb-2edf18cd240e.png)


In addition, another measure for convergence is the beta value graph, once the beta values are going below 0.002 the model starts to converge around the 0 level set, and marching cubes can be extracted. This is the beta value graph of the pre-trained AFHQ model: 
![image](https://user-images.githubusercontent.com/13196935/165506247-4c2c4827-2faf-4315-a19c-7904fc2a3800.png)

**Comment by boduan1** [comment]
> @boduan1
> 
> These images are actually not ok, the model failed to converge. The image quality is not what it should be like and there's no change of pose in the dogs' faces. Here's how the volume renderer outputs should look like when the model is converged: ![image](https://user-images.githubusercontent.com/13196935/165506489-6c47f6ab-f006-4643-a4cb-2edf18cd240e.png)
> 
> In addition, another measure for convergence is the beta value graph, once the beta values are going below 0.002 the model starts to converge around the 0 level set, and marching cubes can be extracted. This is the beta value graph of the pre-trained AFHQ model: ![image](https://user-images.githubusercontent.com/13196935/165506247-4c2c4827-2faf-4315-a19c-7904fc2a3800.png)

Thank you very much for your reply royorel!
I will try to increase the number of iterations to see if it will work for me.
