### ISSUE TITLE
Checkpoints for Resolution at 256

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [royorel/StyleSDF#15]
Hi @royorel , thanks a lot for open-sourcing the code for this great work. I am wondering whether you mind sharing the checkpoints that are trained at the resolution of 256? Since all quantitative results in the paper come from 256 resolution, it would be much appreciated if those checkpoints are available. Thanks

**Comment by royorel** [comment]
Hi @Xiaoming-Zhao,

We don't have 256x256 checkpoints. We resized the 1024x1024 images to 256x256. Also note to **NOT** use mean truncation for FID and KID calculations.

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for the clarification.
