### ISSUE TITLE
a bug about training the full pipeline 1024x1024

### ISSUE THREAD

**Issue by yjh576** [royorel/StyleSDF#19]
Hi! I have a problem about training the full ffhq pipeline 1024x1024. 
![20220715-114645](https://user-images.githubusercontent.com/55342613/179146273-8dc4119b-dac9-4554-b98e-b6e2a55c6574.png)
![20220715-115241](https://user-images.githubusercontent.com/55342613/179146866-352bc6f3-a402-4c86-8736-de9c57ccb086.png)

**Comment by royorel** [comment]
Hi @yjh576,

Can you please specify the exact setup and hyper-parameters you used?

I can't reproduce the bug

**Comment by yjh576** [comment]
I downloaded it directly from your codebase and did not make any changes.

**Comment by royorel** [comment]
I mean what command did you run? and which arguments did you use?

**Comment by royorel** [comment]
@yjh576 I was able to reproduce this issue now, I'm still not sure about the cause, but this may potentially require a fix for the code. I will update once I will resolve this.

Thanks for reporting this issue!!

**Comment by yjh576** [comment]
Pytorch version I used is 1.10.0. Thank you for your help.

**Comment by Ni1r** [comment]
@yjh576 hi ,i met an error when training the volume renderer,Can I take a look at the structure of your dataset ,please?thanks!

**Comment by Ni1r** [comment]
> Hi @Ni1r,
> 
> It would help if you specify the actual error. As for the dataset, before running `prepare_data.py` the dataset should only contain image files. In addition, if you made it through the volume renderer training phase with no issues (I'm assuming you ran that first), then the error is not in your dataset structure.

![2(5JG}`W717VZNZ1UKP2C85](https://user-images.githubusercontent.com/94331546/196429873-f5c9ef2f-8150-49d4-acc1-e89cce1bb2a7.png)
this is my error,before this ,i have run the "prepare_data.py" and get the data.mdb and lock.mdb

**Comment by Ni1r** [comment]
> Hi @Ni1r,
> 
> It would help if you specify the actual error. As for the dataset, before running `prepare_data.py` the dataset should only contain image files. In addition, if you made it through the volume renderer training phase with no issues (I'm assuming you ran that first), then the error is not in your dataset structure.

![20B9BECDB0BB5F8FE89F7300E760A85B](https://user-images.githubusercontent.com/94331546/196430470-6aed4aa1-9058-47e6-9717-5d3cde864cfc.png)
this is my error,before this ,i have run the "prepare_data.py" and get the data.mdb and lock.mdb
![C_H}`PP`J%4SR~6{CG2)KQ2](https://user-images.githubusercontent.com/94331546/196430590-f603974e-c924-42bd-85da-627f28474298.png)
