### ISSUE TITLE
train_volume_renderer.py not found 

### ISSUE THREAD

**Issue by Len-Li** [royorel/StyleSDF#2]
Hi, thanks for sharing your awesome work!
I try to train the full pipeline. It seems like all training scripts are missing, such as train_volume_renderer.py and train_full_pipeline.py. Could you check it out?

**Comment by royorel** [comment]
As we pointed out in our tweet, right now only the testing part is available.

The training files are missing right now since we are still making sure that they work properly after the cleanup and reproduce the results.

We will release the training files soon, stay tuned.

**Comment by vkmavani** [comment]
> As we pointed out in our tweet, right now only the testing part is available.
> 
> The training files are missing right now since we are still making sure that they work properly after the cleanup and reproduce the results.
> 
> We will release the training files soon, stay tuned.

Please, share it with a training demo notebook of colab.

**Comment by royorel** [comment]
@vkmavani,

Training is designed to be run on multiple GPUs and therefore not suitable for a colab notebook. 
You can use the provided training scripts to train the networks.
