### ISSUE TITLE
Is there any pretrained model on lower-resolution FFHQ?

### ISSUE THREAD

**Issue by StellEdge** [royorel/StyleSDF#21]
Hi, I wonder if we have an available pretrained StyleSDF model for 256x256 FFHQ? As a StyleGAN based model, its full model is too big to start with. A 256x256 FFHQ based model will be very helpful.

**Comment by royorel** [comment]
Hi @StellEdge,

There is no pre-trained 256x256 model, but you can use the pre-trained volume renderers and only train the decoder part at 256x256 resolution.
