### ISSUE TITLE
About sphere init

### ISSUE THREAD

**Issue by MontaEllis** [royorel/StyleSDF#29]
Hello! Do you update beta while initializing?

**Comment by royorel** [comment]
No, beta is only updated during training.

**Comment by MontaEllis** [comment]
But how to keep beta unupdated during initializing?

**Comment by royorel** [comment]
See lines 60-89 in train_volume_renderer.py. There is a designated function for that that does not involve beta in the forward pass.

**Comment by MontaEllis** [comment]
Thanks a lot!
