### ISSUE TITLE
Strange colors on output

### ISSUE THREAD

**Issue by richardburleigh** [royorel/StyleSDF#6]
Thank you for releasing this code, you have done an amazing job!

I am receiving strange colors on the RGB output for a custom dataset that does not happen on the thumbnails, but am unable to figure out exactly why.

The RGB images generated are almost entirely pink and red, however the thumbnails are fine.

Any ideas would be sincerely appreciated!

Edit: It seems this was only an issue when training the volume renderer.. full pipeline seems fine.. closing the issue :-D

**Comment by royorel** [comment]
Hi @richardburleigh,

Can you elaborate on that, or share a screen capture? Does it happen on wandb? 

When you train the volume renderer the full scale images should not be generated at all, so that might be an issue that I will need to look at.
